version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b1:39:d0:ee:75:8a:4f:ca:88:b2:03:89:46:17:84:13"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "/opt/software/chaddi-api/scripts/deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master